export type Faculty =
  | "Allied Health Sciences"
  | "Arts"
  | "Basic Medical Sciences"
  | "Clinical Sciences"
  | "Dentistry"
  | "Education"
  | "Engineering"
  | "Law"
  | "Management Sciences"
  | "Science"
  | "Social Sciences"
  | "Transport";

export type Department =
  | "Accounting"
  | "Aeronautics and Astronautics Engineering"
  | "Aerospace Engineering"
  | "African Language, Lit & Comms"
  | "Anasthesia"
  | "Anatomy"
  | "Banking and Finance"
  | "Behavioural Medicine"
  | "Biochemistry"
  | "Botany"
  | "Business Administration"
  | "Business Law"
  | "Chemical Engineering"
  | "Chemical Pathology"
  | "Chemistry"
  | "Child Dental Health"
  | "Community Health and Primary Care"
  | "Computer Science"
  | "Economics"
  | "Educational Foundations and Counselling Psychology"
  | "Educational Management"
  | "Electronics and Computer Engineering"
  | "English Language"
  | "Fisheries"
  | "Foreign Languages"
  | "Geography & Planning"
  | "Hematology and Blood Tranfusion"
  | "History and International Relations"
  | "Human Kinetic & H.E"
  | "Industrial Relations and Personnel Management"
  | "Insurance"
  | "International and Islamic Law"
  | "Jurisprudence and International Law"
  | "Lang, Arts AND Sci"
  | "Law"
  | "Local Government Administration and Development Studies"
  | "Management Technology"
  | "Marketing"
  | "Mathematics"
  | "Mechanical Engineering"
  | "Medical Biochemistry"
  | "Medical Laboratory Sciences"
  | "Medical Microbiology and Parasitology"
  | "Medicine"
  | "Microbiology"
  | "Music"
  | "Nursing"
  | "Obstetrics and Gynaecology"
  | "Oral Pathology / Oral Medicine"
  | "Oral and Maxillofacial Surgery"
  | "Pathology and Forensic Medicine"
  | "Pediatrics and Child Health"
  | "Pharmacology"
  | "Philosophy"
  | "Physics"
  | "Physiology"
  | "Physiotherapy"
  | "Political Science"
  | "Post Graduate School"
  | "Preventive Dentistry"
  | "Psychology"
  | "Public Administration"
  | "Public and Private Law"
  | "Radiography"
  | "Radiology"
  | "Religions"
  | "Restorative Dentistry"
  | "Science Laboratory Technology"
  | "Science and Tech. Education"
  | "Sociology"
  | "Surgery"
  | "Theatre Arts"
  | "Transport Management and Operations"
  | "Transport Planning and Policy"
  | "Transport Technology and Infrastructure"
  | "Zoology and Environmental Biology";
